# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "b6:57:0b:30:a9:80:38:29:9f:08:8e:f6:3f:7e:99:d4" 
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install requests

      
      - run:
          name: run script
          command: |
            . venv/bin/activate
            python scripts/h1.py


      - run:
          name: Commit data back to Github
          command: |
            git config user.email "avicoder@outlook.com"
            git config user.name "avicoder"
            DATE_TODAY=$(date +"%Y-%m-%d")
            git pull origin master
            git commit -am "[skip ci] Updating Data ${DATE_TODAY}" --allow-empty
            git push origin master
